module NetboxExtractor
  module Generators
    class Ansible
      Log = ::Log.for("netbox-extractor.ansible")

      def self.run(site)
        device_inventory = NetboxExtractor::Netbox::DeviceInventory.new(site)
        vm_inventory = NetboxExtractor::Netbox::VmInventory.new(site)
        generator = new(site, device_inventory, vm_inventory)
        generator.run
      end

      def initialize(@site : NetboxExtractor::Config::Site,
                     @device_inventory : NetboxExtractor::Netbox::DeviceInventory,
                     @vm_inventory : NetboxExtractor::Netbox::VmInventory)
        set_log_context!
      end

      def run
        @device_inventory.load!
        @vm_inventory.load!
        generate_files
      end

      private def set_log_context!
        Log.context.set site: @site.id
      end

      private def generate_files
        NetboxExtractor::Concurrency.each_isolated(@site.ansible.include_device_roles, "Ansible device inventory (site #{@site.id})") do |role|
          # log context is per fiber
          set_log_context!

          ansible_dump_devices(role: role.name, filename: role.filename)
        end

        NetboxExtractor::Concurrency.each_isolated(@site.ansible.include_vm_roles, "Ansible vm inventory (site #{@site.id})") do |role|
          # log context is per fiber
          set_log_context!

          ansible_dump_vms(role: role.name, os: role.os, filename: role.filename)
        end
      end

      private def ansible_dump_devices(role, filename = nil)
        inventory = @device_inventory.fetch_devices(role: role)
        filename ||= role
        inventory_file = @site.ansible_inventory_path.join("#{filename}.yml")

        if inventory.empty?
          Log.warn { "Skipping Ansible inventory for '#{role}': no hosts" }
          File.delete(inventory_file) if File.exists?(inventory_file)
        else
          Log.info { "Generating Ansible inventory for '#{role}'" }

          ansible_dump(inventory: inventory, inventory_file: inventory_file)
        end
      end

      private def ansible_dump_vms(role, os, filename)
        inventory = @vm_inventory.fetch_vms(role: role, os: os)
        filename ||= role
        inventory_file = @site.ansible_inventory_path.join("#{filename}.yml")

        if inventory.empty?
          Log.warn { "Skipping Ansible inventory for '#{role}': no hosts" }
          File.delete(inventory_file) if File.exists?(inventory_file)
        else
          Log.info { "Generating Ansible inventory for '#{role}'" }

          ansible_dump(inventory: inventory, inventory_file: inventory_file)
        end
      end

      # Preserves the user-editable `vars:` block across regeneration, falling
      # back to an empty document if the existing file is missing or corrupt
      # rather than aborting the fiber (C5).
      private def load_existing_inventory(inventory_file)
        return YAML.parse("{}") unless File.exists?(inventory_file)

        YAML.parse(File.read(inventory_file))
      rescue ex : YAML::ParseException | IO::Error
        Log.warn { "Ignoring unreadable inventory #{inventory_file}: #{ex.message}" }
        YAML.parse("{}")
      end

      private def ansible_dump(inventory, inventory_file)
        current_inventory = load_existing_inventory(inventory_file)

        vars = current_inventory.dig?("all", "vars") || {} of String => String
        hosts = inventory.map { |host| to_ansible(host) }
        new_inventory = to_ansible_inventory(hosts, vars)

        write_to_file(inventory_file, YAML.dump(new_inventory))
      end

      private def to_ansible(host)
        presenter = NetboxExtractor::Presenters::Ansible.new(@site, host)
        presenter.to_ansible
      end

      private def to_ansible_inventory(hosts, vars)
        data = NetboxExtractor::RecursiveHash.new

        hosts.each do |item|
          item.each do |key, value|
            if key && value
              data[key] = value
            end
          end
        end

        {"all" => {"vars" => vars, "hosts" => data}}
      end

      private def write_to_file(file, data)
        Log.debug { "writing file: #{file}" }

        dir = File.dirname(file)
        Dir.mkdir_p(dir) unless Dir.exists?(dir)

        File.open(file, "w") do |f|
          f.puts ansible_banner
          f.puts data
        end
      end

      private def ansible_banner
        <<-BANNER
        # THIS FILE IS GENERATED BY bin/netbox-extractor
        # You can modify the 'vars:' section but you can't modify the 'hosts:' section
        # or it will overwritten on the next call to bin/netbox-extractor
        BANNER
      end
    end
  end
end
