require "./base"

module NetboxExtractor
  # :nodoc:
  module Generators
    class Ansible < Base
      Log = ::Log.for("netbox-extractor.ansible")

      private def generate_files
        WaitGroup.wait do |wg|
          @site.ansible.include_device_roles.each do |role|
            wg.spawn { ansible_dump_devices(role: role.name, filename: role.filename) }
          end
        end

        WaitGroup.wait do |wg|
          @site.ansible.include_vm_roles.each do |role|
            wg.spawn { ansible_dump_vms(role: role.name, os: role.os, filename: role.filename) }
          end
        end
      end

      private def ansible_dump_devices(role, filename = nil)
        inventory = @inventory_loader.fetch_devices(role: role)

        if inventory.empty?
          Log.warn { "[#{@site.id}] Skipping Ansible inventory for '#{role}': no hosts" }
        else
          Log.info { "[#{@site.id}] Generating Ansible inventory for '#{role}'" }

          filename ||= role
          inventory_file = @site.ansible_inventory_path.join("#{filename}.yml")
          ansible_dump(inventory: inventory, inventory_file: inventory_file)
        end
      end

      private def ansible_dump_vms(role, os, filename)
        inventory = @inventory_loader.fetch_vms(role: role, os: os)

        if inventory.empty?
          Log.warn { "[#{@site.id}] Skipping Ansible inventory for '#{role}': no hosts" }
        else
          Log.info { "[#{@site.id}] Generating Ansible inventory for '#{role}'" }

          filename ||= role
          inventory_file = @site.ansible_inventory_path.join("#{filename}.yml")
          ansible_dump(inventory: inventory, inventory_file: inventory_file)
        end
      end

      private def ansible_dump(inventory, inventory_file)
        current_inventory = File.exists?(inventory_file) ? YAML.parse(File.read(inventory_file)) : {} of String => String

        vars = current_inventory.dig?("all", "vars") || {} of String => String
        hosts = inventory.map { |host| to_ansible(host) }
        new_inventory = to_ansible_inventory(hosts, vars)

        write_to_file(inventory_file, YAML.dump(new_inventory))
      end

      private def to_ansible(host)
        presenter = NetboxExtractor::Presenters::Ansible.new(@site, host)
        presenter.to_ansible
      end

      private def to_ansible_inventory(hosts, vars)
        data = NetboxExtractor::RecursiveHash.new

        hosts.each do |item|
          item.each do |key, value|
            if key && value
              data[key] = value
            end
          end
        end

        {"all" => {"vars" => vars, "hosts" => data}}
      end

      private def write_to_file(file, data)
        Log.debug { "[#{@site.id}] writing file: #{file}" }

        dir = File.dirname(file)
        Dir.mkdir_p(dir) unless Dir.exists?(dir)

        File.open(file, "w") do |f|
          f.puts ansible_banner
          f.puts data
        end
      end

      private def ansible_banner
        <<-BANNER
        # THIS FILE IS GENERATED BY bin/netbox-extractor
        # You can modify the 'vars:' section but you can't modify the 'hosts:' section
        # or it will overwritten on the next call to bin/netbox-extractor
        BANNER
      end
    end
  end
end
