module NetboxExtractor
  module Generators
    # Bind DNS zone generator. Currently a stub: it loads IPAM addresses and dumps
    # them to STDOUT as YAML, writing no actual zone file.
    class Bind
      Log = ::Log.for("netbox-extractor.bind")

      # Convenience entry point: builds the IPAM inventory and runs the generator.
      def self.run
        ipam_inventory = NetboxExtractor::Netbox::IpamInventory.new
        inventory_generator = new(ipam_inventory)
        inventory_generator.run
      end

      # Injects the (already constructed) IPAM inventory, allowing tests to supply
      # a double.
      def initialize(@ipam_inventory : NetboxExtractor::Netbox::IpamInventory)
      end

      # Loads the IPAM inventory and dumps the IP list to STDOUT (stub behaviour).
      def run
        Log.warn { "Bind zone generation is a stub: it dumps the IP list to STDOUT and writes no zone file" }

        @ipam_inventory.load!
        generate_files
      end

      private def generate_files
        ips = @ipam_inventory.fetch_ips.map(&.display)
        puts Bind.dump(ips)
      end

      # Renders the IP list as YAML behind the generated-file banner. Kept free of
      # I/O so the rendering is exercised without a Netbox instance; the banner
      # is a YAML comment, so a redirected dump stays parseable.
      def self.dump(ips)
        String.build do |io|
          io << "# This file is generated by netbox-extractor - do not edit, it will be overwritten.\n"
          io << YAML.dump(ips)
        end
      end
    end
  end
end
