require "../../spec_helper"

Spectator.describe NetboxExtractor::Generators::Bind do
  # The dump is meant to be redirected into a file, so it carries the same
  # generated-file banner as every other output of the tool. Rendering it
  # separately from the `puts` keeps the banner assertion free of STDOUT capture.
  describe ".dump" do
    it "prefixes the YAML dump with the generated-file banner" do
      output = NetboxExtractor::Generators::Bind.dump(["10.0.0.1/24"])

      expect(output.lines.first).to eq("# This file is generated by netbox-extractor - do not edit, it will be overwritten.")
      expect(output).to contain("10.0.0.1/24")
    end

    it "stays valid YAML" do
      output = NetboxExtractor::Generators::Bind.dump(["10.0.0.1/24", "10.0.0.2/24"])

      expect(YAML.parse(output).as_a.map(&.as_s)).to eq(["10.0.0.1/24", "10.0.0.2/24"])
    end
  end
end
